# Generated by Django 4.2.5 on 2023-09-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutData',
            new_name='Services',
        ),
    ]
