# Generated by Django 4.2.5 on 2023-09-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='request',
            field=models.TextField(max_length=1000),
        ),
    ]
