# Generated by Django 4.2.5 on 2023-09-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_application_email_alter_application_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
