# Generated by Django 4.2.5 on 2023-09-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_projects_project_rename_services_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
